# Starship configuration - let terminal handle colors

format = "$directory$python $git_branch$character"

add_newline = false

[directory]
format = "[$path]($style)"
truncation_length = 1

[python]
format = '[.venv]($style) '
symbol = ""

[git_branch]
format = "git:($branch)"

[character]
format = " $symbol "
success_symbol = "➜"
error_symbol = "➜"
